image_size = 256
max_triplets = 5
temperature = 1
seed = 3

image_dir = "./data/things-behavior-images/"
train_fp = "./data/1k_filtered_triplets.txt" # we need to merge the train and test files at the end

concept_fp = "./data/things_concepts.tsv"
non_unique_words_fp = "./data/NonUniqueWords_edited.xlsx"

output_fp = "./gpt4_test_10.pkl"

compute_noise_ceilings = false
extract_responses = true

